subscribers:

  camera_reading:
    topic: /hardware/depth/kinect2/hd/image_color_rect
    queue_size: 1

actions:

  camera_reading:
    name: /darknet_ros/check_for_objects

publishers:

  object_detector:
    topic: /darknet_ros/found_object_kinect
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /darknet_ros/bounding_boxes_kinect
    queue_size: 1
    latch: false

  detection_image:
    topic: /darknet_ros/detection_image_kinect
    queue_size: 1
    latch: false

image_view:

  enable_opencv: false
  wait_key_delay: 1
  enable_console_output: false
